package harness

import (
	"fmt"
	"sort"
	"strings"
	"unicode"
)

// RenderEnvScript renders environment assignments as the PowerShell script a
// goblin dot-sources to take project credentials refreshed after its spawn.
// Keeping the values in a file rather than in a typed line is what keeps a
// credential out of the terminal's scrollback.
func RenderEnvScript(env map[string]string) (string, error) {
	keys := make([]string, 0, len(env))
	for key := range env {
		if !ValidEnvironmentName(key) {
			return "", fmt.Errorf("harness: invalid environment name %q", key)
		}
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var script strings.Builder
	script.WriteString("# Generated by cfo spawn. Project credentials for this task's pane.\n")
	// A harness that finds its own billing key in the environment
	// authenticates with it instead of the Supreme Overlord's subscription,
	// and every token it spends bills that key. Strip each such name before
	// the harness starts, whatever put it there: an inherited user or
	// machine variable, a dot-sourced project file, or a shell profile. The
	// injection guard in auth.InjectEnv keeps a manifest from adding one;
	// this keeps everything else from leaving one behind.
	for _, key := range HarnessBillingKeys {
		script.WriteString("Remove-Item -Path Env:" + key + " -ErrorAction SilentlyContinue\n")
	}
	for _, key := range keys {
		script.WriteString("$env:" + key + " = " + powerShellLiteral(env[key]) + "\n")
	}
	return script.String(), nil
}

// HarnessBillingKeys are the variables a coding harness reads as its own
// authentication. The credential script removes every one of them, so a
// goblin that sources it can only run on the subscription. Kept
// here rather than in the auth package so the harness contract owns the
// list; auth.IsHarnessBillingKey consults it for the injection guard.
var HarnessBillingKeys = []string{
	"ANTHROPIC_API_KEY",
	"ANTHROPIC_AUTH_TOKEN",
	"CLAUDE_API_KEY",
	"OPENAI_API_KEY",
	"OPENAI_KEY",
	"CODEX_API_KEY",
	"MOONSHOT_API_KEY",
	"KIMI_API_KEY",
	"GEMINI_API_KEY",
	"GOOGLE_API_KEY",
}

func powerShellLiteral(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

// ValidEnvironmentName reports whether name can be assigned as $env:name in
// a PowerShell script. It is the single rule for environment names: rendering
// enforces it, and a worktree manifest's env redirects are validated against it
// at resolve time, so a bad name is refused before anything is stopped or
// provisioned rather than at launch.
func ValidEnvironmentName(name string) bool {
	for index, character := range name {
		if character == '_' || unicode.IsLetter(character) || (index > 0 && unicode.IsDigit(character)) {
			continue
		}
		return false
	}
	return name != ""
}
